-- Add missing columns to Online_Orders
ALTER TABLE Online_Orders
ADD COLUMN IF NOT EXISTS order_code VARCHAR(50) UNIQUE,
ADD COLUMN IF NOT EXISTS customer_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(50),
ADD COLUMN IF NOT EXISTS shipping_address TEXT,
ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50),
ADD COLUMN IF NOT EXISTS payment_details JSONB,
ADD COLUMN IF NOT EXISTS subtotal DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS shipping DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tracking_no VARCHAR(100),
ADD COLUMN IF NOT EXISTS delivery_provider VARCHAR(100);

-- Add missing columns to POS_Transactions
ALTER TABLE POS_Transactions
ADD COLUMN IF NOT EXISTS cashier_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);

-- Create Coupons table
CREATE TABLE IF NOT EXISTS Coupons (
  id SERIAL PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  type VARCHAR(50) DEFAULT 'percentage',
  value DECIMAL(10,2) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
